on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    - uses: hbrzbj/zmk-config/.github/workflows/build-user-config.yml@master

      # - name: Publish release
      #   uses: eloquent/github-release-action@v2
      # - name: Upload images to Releases
      #   uses: svenstaro/upload-release-action@2.2.0
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: build/artifacts/*.uf2
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     file_glob: true
  release:
    needs: build
    steps:
      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.RELEASE_DATE}}"
          title: ${{ env.ReleaseVersion }}
          prerelease: false
          files: |
            build/artifacts/*
